FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
WORKDIR /app

# Copy everything else and build
COPY . ./
#RUN dotnet restore
RUN dotnet build
RUN mkdir -p Reports

#Sonar
RUN dotnet tool install --global dotnet-sonarscanner
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/app/Reports/Coverage/
RUN dotnet sonarscanner begin /k:SampleDotNetCore2RestStub /d:sonar.host.url=https://sonarqube-rg.azurewebsites.net /d:sonar.cs.opencover.reportsPaths=/app/Reports/Coverage/coverage.opencover.xml /d:sonar.coverage.exclusions=”**Test*.cs”
RUN dotnet build
RUN dotnet sonarscanner end

ENTRYPOINT dotnet test --logger 'trx;LogFileName=TestResults.trx' --results-directory /app/Reports/UnitTests /p:CollectCoverage=true /p:CoverletOutput=/app/Reports/Coverage/ /p:CoverletOutputFormat=cobertura
